package com.arkeomag.app;

import android.Manifest;
import android.app.*;import android.os.*;import android.hardware.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.Typeface;import android.location.*;import android.media.*;import android.view.*;import android.widget.*;import android.bluetooth.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener, LocationListener{
    SensorManager sm; Sensor mag,acc,gyro,rot; LocationManager lm; BluetoothAdapter bt;
    float[] m=new float[3], a=new float[3], g=new float[3], base=new float[3], minCal={9999,9999,9999}, maxCal={-9999,-9999,-9999};
    boolean hasBase=false, alarm=true, recording=false; float threshold=8f, sensitivity=1.4f; long lastBeep=0; ToneGenerator tone; Vibrator vib; Location lastLoc;
    ArrayList<Sample> samples=new ArrayList<Sample>(); String mode="DETECTOR";
    LinearLayout root, content, nav; TextView title,status,xyz,total,delta,tilt,gps,quality,count,btInfo; GaugeView gauge; GraphView graph; BarView bars; ModelView model; HeatMapView heat; SonarView sonar;
    int bg=Color.rgb(5,12,24), card=Color.rgb(12,27,46), card2=Color.rgb(18,41,70), green=Color.rgb(61,220,132), yellow=Color.rgb(255,210,80), red=Color.rgb(255,88,88), cyan=Color.rgb(80,220,255);
    Typeface digitalFont; Bitmap triGrid;
    @Override public void onCreate(Bundle b){super.onCreate(b); try{digitalFont=Typeface.createFromAsset(getAssets(),"fonts/digital.ttf");}catch(Exception ex){digitalFont=Typeface.MONOSPACE;} try{triGrid=BitmapFactory.decodeStream(getAssets().open("original/models/trigrid.png"));}catch(Exception ex){} sm=(SensorManager)getSystemService(SENSOR_SERVICE); lm=(LocationManager)getSystemService(LOCATION_SERVICE); bt=BluetoothAdapter.getDefaultAdapter(); mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD); acc=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER); gyro=sm.getDefaultSensor(Sensor.TYPE_GYROSCOPE); rot=sm.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR); tone=new ToneGenerator(AudioManager.STREAM_MUSIC,70); vib=(Vibrator)getSystemService(VIBRATOR_SERVICE); requestPerms(); buildUi(); showDetector();}
    void requestPerms(){ if(Build.VERSION.SDK_INT>=23) requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.VIBRATE,Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},5); }
    TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(18,8,18,8);return v;}
    void numeric(TextView v){ if(v!=null && digitalFont!=null) v.setTypeface(digitalFont); }
    Button btn(String s){Button b=new Button(this); b.setText(s); b.setAllCaps(false); return b;}
    void buildUi(){ScrollView sv=new ScrollView(this); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(14,14,14,14); root.setBackgroundColor(bg); sv.addView(root); title=tv("ArkeoMag Pro — Temiz / Girişsiz",23); title.setTextColor(green); title.setTypeface(Typeface.DEFAULT_BOLD); root.addView(title); TextView sub=tv("Dedektör • Kalibrasyon • Live Scan • Area Scan • Sonar/3D • CSV • Bluetooth",13); sub.setTextColor(cyan); root.addView(sub); nav=new LinearLayout(this); nav.setOrientation(LinearLayout.HORIZONTAL); root.addView(nav); addNav("Dedektör","DETECTOR"); addNav("Kalibrasyon","CAL"); addNav("Live","LIVE"); addNav("Alan","AREA"); addNav("Sonar/3D","SONAR"); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); root.addView(content); setContentView(sv);}
    void addNav(String text, final String m){Button b=btn(text); b.setTextSize(11); b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){mode=m; if(m.equals("DETECTOR"))showDetector(); else if(m.equals("CAL"))showCal(); else if(m.equals("LIVE"))showLive(); else if(m.equals("AREA"))showArea(); else showSonar();}}); nav.addView(b,new LinearLayout.LayoutParams(0,80,1));}
    void clear(){content.removeAllViews();}
    void common(){status=tv("Durum: Android native sensör",16); content.addView(status); xyz=tv("X/Y/Z: 0",19); numeric(xyz); content.addView(xyz); total=tv("|B|: 0 µT",22); numeric(total); content.addView(total); delta=tv("Sapma: 0 µT",31); numeric(delta); delta.setTextColor(green); content.addView(delta); tilt=tv("Accel/Gyro: 0",14); content.addView(tilt); gps=tv("GPS: bekleniyor",14); content.addView(gps);}
    void showDetector(){clear(); content.addView(tv("DEDEKTÖR MODU",18)); common(); gauge=new GaugeView(this); content.addView(gauge,new LinearLayout.LayoutParams(-1,330)); bars=new BarView(this); content.addView(bars,new LinearLayout.LayoutParams(-1,210)); graph=new GraphView(this); content.addView(graph,new LinearLayout.LayoutParams(-1,260)); LinearLayout row=new LinearLayout(this); row.setOrientation(LinearLayout.HORIZONTAL); Button zero=btn("Taban Sıfırla"); zero.setOnClickListener(new View.OnClickListener(){public void onClick(View v){System.arraycopy(m,0,base,0,3);hasBase=true;toast("Referans alındı");}}); Button al=btn(alarm?"Alarm Açık":"Alarm Kapalı"); al.setOnClickListener(new View.OnClickListener(){public void onClick(View v){alarm=!alarm;((Button)v).setText(alarm?"Alarm Açık":"Alarm Kapalı");}}); row.addView(zero,new LinearLayout.LayoutParams(0,95,1)); row.addView(al,new LinearLayout.LayoutParams(0,95,1)); content.addView(row); SeekBar seek=new SeekBar(this); seek.setMax(40); seek.setProgress((int)threshold); seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){threshold=Math.max(1,p);status.setText("Eşik: "+threshold+" µT");} public void onStartTrackingTouch(SeekBar s){} public void onStopTrackingTouch(SeekBar s){}}); content.addView(tv("Hassasiyet / alarm eşiği",14)); content.addView(seek);}
    void showCal(){clear(); content.addView(tv("KALİBRASYON MODU",18)); common(); quality=tv("Kalibrasyon kalite: bekleniyor",20); quality.setTextColor(cyan); content.addView(quality); content.addView(tv("Telefonu 8 çizerek ve 3 eksende yavaşça çevir. Min/max değerleri toplanır, hard-iron offset hesaplanır.",15)); graph=new GraphView(this); content.addView(graph,new LinearLayout.LayoutParams(-1,260)); bars=new BarView(this); content.addView(bars,new LinearLayout.LayoutParams(-1,240)); Button reset=btn("Kalibrasyonu Sıfırla"); reset.setOnClickListener(new View.OnClickListener(){public void onClick(View v){for(int i=0;i<3;i++){minCal[i]=9999;maxCal[i]=-9999;base[i]=0;}hasBase=false;toast("Kalibrasyon sıfırlandı");}}); Button apply=btn("Hard-Iron Offset Uygula"); apply.setOnClickListener(new View.OnClickListener(){public void onClick(View v){for(int i=0;i<3;i++)base[i]=(minCal[i]+maxCal[i])/2f;hasBase=true;toast("Offset uygulandı");}}); content.addView(reset,new LinearLayout.LayoutParams(-1,90)); content.addView(apply,new LinearLayout.LayoutParams(-1,90));}
    void showLive(){clear(); content.addView(tv("LIVE SCAN",18)); common(); count=tv("Kayıt: 0 nokta",20); content.addView(count); graph=new GraphView(this); content.addView(graph,new LinearLayout.LayoutParams(-1,280)); Button rec=btn("Sürekli Kayıt Başlat/Durdur"); rec.setOnClickListener(new View.OnClickListener(){public void onClick(View v){recording=!recording;((Button)v).setText(recording?"Kayıt Durdur":"Sürekli Kayıt Başlat");}}); Button point=btn("Nokta Kaydet"); point.setOnClickListener(new View.OnClickListener(){public void onClick(View v){addSample();}}); Button csv=btn("CSV Dışa Aktar"); csv.setOnClickListener(new View.OnClickListener(){public void onClick(View v){exportCsv();}}); content.addView(rec,new LinearLayout.LayoutParams(-1,90)); content.addView(point,new LinearLayout.LayoutParams(-1,90)); content.addView(csv,new LinearLayout.LayoutParams(-1,90));}
    void showArea(){clear(); content.addView(tv("AREA SCAN / GRID",18)); common(); count=tv("Alan tarama grid: 0 nokta",20); content.addView(count); heat=new HeatMapView(this); content.addView(heat,new LinearLayout.LayoutParams(-1,520)); content.addView(tv("Yürüme/grid modu: her noktada 'Nokta Kaydet' ile manyetik değer + GPS saklanır. Isı haritası sapmaya göre çizilir.",15)); Button point=btn("Grid Noktası Kaydet"); point.setOnClickListener(new View.OnClickListener(){public void onClick(View v){addSample(); if(heat!=null)heat.invalidate();}}); Button clear=btn("Grid Temizle"); clear.setOnClickListener(new View.OnClickListener(){public void onClick(View v){samples.clear(); if(heat!=null)heat.invalidate(); updateCount();}}); Button csv=btn("CSV Dışa Aktar"); csv.setOnClickListener(new View.OnClickListener(){public void onClick(View v){exportCsv();}}); content.addView(point,new LinearLayout.LayoutParams(-1,90)); content.addView(clear,new LinearLayout.LayoutParams(-1,90)); content.addView(csv,new LinearLayout.LayoutParams(-1,90));}
    void showSonar(){clear(); content.addView(tv("SONAR / 3D MODEL",18)); common(); sonar=new SonarView(this); content.addView(sonar,new LinearLayout.LayoutParams(-1,360)); model=new ModelView(this); content.addView(model,new LinearLayout.LayoutParams(-1,430)); btInfo=tv("Bluetooth: tarama yapılmadı",15); content.addView(btInfo); Button scan=btn("Bluetooth Cihazlarını Listele"); scan.setOnClickListener(new View.OnClickListener(){public void onClick(View v){listBt();}}); content.addView(scan,new LinearLayout.LayoutParams(-1,90)); content.addView(tv("Aktarılan varlıklar: digital font, shader dosyaları, trigrid model dokusu, eski layout referansları. Kullanıcı girişi/Firebase/Play Integrity yok.",13)); content.addView(tv("3D/sonar görünüm relatif manyetik anomaliyi görselleştirir; gerçek derinlik ölçümü değildir.",14));}
    @Override protected void onResume(){super.onResume(); if(mag!=null)sm.registerListener(this,mag,SensorManager.SENSOR_DELAY_GAME); if(acc!=null)sm.registerListener(this,acc,SensorManager.SENSOR_DELAY_GAME); if(gyro!=null)sm.registerListener(this,gyro,SensorManager.SENSOR_DELAY_GAME); try{ if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED) lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000,0,this);}catch(Exception e){} }
    @Override protected void onPause(){super.onPause(); sm.unregisterListener(this); try{lm.removeUpdates(this);}catch(Exception e){} }
    @Override public void onAccuracyChanged(Sensor s,int ac){}
    @Override public void onSensorChanged(SensorEvent e){ if(e.sensor.getType()==Sensor.TYPE_MAGNETIC_FIELD){m=e.values.clone(); for(int i=0;i<3;i++){if(m[i]<minCal[i])minCal[i]=m[i]; if(m[i]>maxCal[i])maxCal[i]=m[i];} update();} else if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER){a=e.values.clone();} else if(e.sensor.getType()==Sensor.TYPE_GYROSCOPE){g=e.values.clone();}}
    float norm(float[] v){return (float)Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);}
    float deltaVal(){ if(!hasBase)return 0; float dx=m[0]-base[0],dy=m[1]-base[1],dz=m[2]-base[2]; return (float)Math.sqrt(dx*dx+dy*dy+dz*dz)*sensitivity; }
    void update(){float b=norm(m),d=deltaVal(); if(xyz!=null)xyz.setText(String.format(Locale.US,"X: %.2f  Y: %.2f  Z: %.2f µT",m[0],m[1],m[2])); if(total!=null)total.setText(String.format(Locale.US,"|B|: %.2f µT",b)); if(delta!=null){delta.setText(String.format(Locale.US,"Sapma: %.2f µT",d)); delta.setTextColor(d<5?green:d<15?yellow:red);} if(tilt!=null)tilt.setText(String.format(Locale.US,"Accel: %.1f %.1f %.1f   Gyro: %.2f %.2f %.2f",a[0],a[1],a[2],g[0],g[1],g[2])); if(gps!=null)gps.setText(lastLoc==null?"GPS: bekleniyor":String.format(Locale.US,"GPS: %.6f, %.6f  ±%.0fm",lastLoc.getLatitude(),lastLoc.getLongitude(),lastLoc.getAccuracy())); String lvl=d<5?"Düşük":d<15?"Orta":d<30?"Yüksek":"Çok yüksek"; if(status!=null)status.setText("Hedef gücü: "+lvl+" | Eşik: "+threshold+" µT | sensör: "+(mag==null?"yok":"aktif")); if(gauge!=null){gauge.value=d;gauge.invalidate();} if(graph!=null)graph.add(d); if(bars!=null){bars.x=m[0]-base[0];bars.y=m[1]-base[1];bars.z=m[2]-base[2];bars.invalidate();} if(model!=null){model.value=d;model.invalidate();} if(sonar!=null){sonar.add(d);} if(quality!=null){float rx=maxCal[0]-minCal[0],ry=maxCal[1]-minCal[1],rz=maxCal[2]-minCal[2];float q=Math.min(100,(rx+ry+rz));quality.setText(String.format(Locale.US,"Kalibrasyon kalite: %.0f/100  Aralık X %.1f Y %.1f Z %.1f",q,rx,ry,rz));} if(recording && System.currentTimeMillis()%700<80)addSample(); if(alarm&&d>threshold&&System.currentTimeMillis()-lastBeep>Math.max(90,650-(int)d*10)){tone.startTone(ToneGenerator.TONE_PROP_BEEP,65); if(vib!=null){if(Build.VERSION.SDK_INT>=26)vib.vibrate(VibrationEffect.createOneShot(35,VibrationEffect.DEFAULT_AMPLITUDE)); else vib.vibrate(35);} lastBeep=System.currentTimeMillis();}}
    void addSample(){Sample s=new Sample();s.t=System.currentTimeMillis();s.x=m[0];s.y=m[1];s.z=m[2];s.total=norm(m);s.delta=deltaVal(); if(lastLoc!=null){s.lat=lastLoc.getLatitude();s.lon=lastLoc.getLongitude();s.acc=lastLoc.getAccuracy();} samples.add(s); updateCount(); toast("Nokta kaydedildi: "+samples.size());}
    void updateCount(){ if(count!=null)count.setText("Kayıt: "+samples.size()+" nokta"); }
    void exportCsv(){try{File dir=new File(getExternalFilesDir(null),"exports");dir.mkdirs();File f=new File(dir,"arkeomag_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".csv");PrintWriter pw=new PrintWriter(new FileWriter(f));pw.println("time,lat,lon,gps_acc,x,y,z,total_uT,delta_uT");for(Sample s:samples)pw.println(s.t+","+s.lat+","+s.lon+","+s.acc+","+s.x+","+s.y+","+s.z+","+s.total+","+s.delta);pw.close();toast("CSV kaydedildi: "+f.getAbsolutePath());}catch(Exception e){toast("CSV hata: "+e.getMessage());}}
    void listBt(){try{ if(bt==null){btInfo.setText("Bluetooth yok");return;} StringBuilder sb=new StringBuilder("Bluetooth eşleşmiş cihazlar:\n"); if(Build.VERSION.SDK_INT>=31 && checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){btInfo.setText("Bluetooth izni gerekli");return;} Set<BluetoothDevice> ds=bt.getBondedDevices(); for(BluetoothDevice d:ds) sb.append("• ").append(d.getName()).append("\n").append(d.getAddress()).append("\n"); btInfo.setText(sb.toString()); }catch(Exception e){btInfo.setText("Bluetooth hata: "+e.getMessage());}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override public void onLocationChanged(Location l){lastLoc=l;} public void onProviderEnabled(String p){} public void onProviderDisabled(String p){} public void onStatusChanged(String p,int s,Bundle b){}
    static class Sample{long t;double lat=0,lon=0;float acc=0,x,y,z,total,delta;}
    public class GaugeView extends View{Paint p=new Paint(1);float value=0;GaugeView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,35,35,p);float cx=w/2f,cy=h*.72f,r=Math.min(w*.38f,h*.55f);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(28);p.setColor(Color.DKGRAY);c.drawArc(cx-r,cy-r,cx+r,cy+r,180,180,false,p);p.setColor(value<5?green:value<15?yellow:red);c.drawArc(cx-r,cy-r,cx+r,cy+r,180,Math.min(180,value*4),false,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(44);p.setColor(Color.WHITE);c.drawText(String.format(Locale.US,"%.1f µT",value),cx,cy-15,p);p.setTextSize(24);c.drawText("Anomali Sapması",cx,cy+35,p);}}
    public class GraphView extends View{Paint p=new Paint(1);ArrayList<Float> vals=new ArrayList<Float>();GraphView(Context c){super(c);}void add(float v){vals.add(v);if(vals.size()>120)vals.remove(0);invalidate();}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,32,32,p);p.setColor(Color.GRAY);p.setStrokeWidth(2);for(int i=1;i<5;i++)c.drawLine(25,i*h/5,w-25,i*h/5,p);p.setColor(green);p.setStrokeWidth(5);for(int i=1;i<vals.size();i++){float x1=25+(i-1)*(w-50f)/120f,x2=25+i*(w-50f)/120f;float y1=h-25-Math.min(h-60,vals.get(i-1)*6),y2=h-25-Math.min(h-60,vals.get(i)*6);c.drawLine(x1,y1,x2,y2,p);}p.setTextSize(24);p.setColor(Color.WHITE);c.drawText("Canlı Sinyal",30,42,p);}}
    public class BarView extends View{Paint p=new Paint(1);float x,y,z;BarView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,30,30,p);float[] v={x,y,z};int[] col={red,green,cyan};String[] n={"X","Y","Z"};for(int i=0;i<3;i++){float bh=Math.min(h-70,Math.abs(v[i])*8);p.setColor(col[i]);float left=50+i*(w-100)/3f; c.drawRect(left,h-35-bh,left+70,h-35,p);p.setColor(Color.WHITE);p.setTextSize(23);c.drawText(n[i]+" "+String.format(Locale.US,"%.1f",v[i]),left,h-10,p);}}}
    public class HeatMapView extends View{Paint p=new Paint(1);HeatMapView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,30,30,p);p.setColor(Color.WHITE);p.setTextSize(25);c.drawText("Alan Tarama Isı Haritası",28,42,p);int cols=6;float cell=(w-50)/6f;for(int i=0;i<samples.size();i++){Sample s=samples.get(i);int row=i/cols,col=i%cols;float d=s.delta;p.setColor(d<5?green:d<15?yellow:red);c.drawCircle(35+col*cell+cell/2,80+row*cell+cell/2,Math.max(10,Math.min(cell/2-5,12+d)),p);}}}
    public class SonarView extends View{Paint p=new Paint(1);ArrayList<Float> vals=new ArrayList<Float>();SonarView(Context c){super(c);}void add(float v){vals.add(v);if(vals.size()>40)vals.remove(0);invalidate();}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,30,30,p);float cx=w/2f,cy=h-20;for(int i=1;i<6;i++){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.GRAY);c.drawCircle(cx,cy,i*h/7f,p);}p.setStyle(Paint.Style.FILL);for(int i=0;i<vals.size();i++){float ang=(float)(Math.PI*(i/(float)Math.max(1,vals.size())));float r=Math.min(h-60,60+vals.get(i)*5);p.setColor(vals.get(i)<5?green:vals.get(i)<15?yellow:red);c.drawCircle(cx+(float)Math.cos(ang)*r,cy-(float)Math.sin(ang)*r,8+Math.min(20,vals.get(i)),p);}p.setColor(Color.WHITE);p.setTextSize(24);c.drawText("Sonar Benzeri Anomali Görünümü",28,42,p);}}
    public class ModelView extends View{Paint p=new Paint(1);float value;ModelView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(card);c.drawRoundRect(10,10,w-10,h-10,35,35,p); if(triGrid!=null){p.setAlpha(45);Rect src=new Rect(0,0,triGrid.getWidth(),triGrid.getHeight());RectF dst=new RectF(25,60,w-25,h-60);c.drawBitmap(triGrid,src,dst,p);p.setAlpha(255);} p.setColor(Color.WHITE);p.setTextSize(25);c.drawText("Relatif 3D Hacim / ModelSurface",28,42,p);float cx=w/2f,cy=h/2f;for(int z=0;z<5;z++){float scale=1-z*.12f;float r=45+value*3-z*10;p.setColor(value<5?green:value<15?yellow:red);p.setAlpha(90+z*25);c.drawOval(cx-r*scale,cy-r*.55f*scale-z*22,cx+r*scale,cy+r*.55f*scale-z*22,p);}p.setAlpha(255);p.setColor(Color.LTGRAY);p.setTextSize(20);c.drawText("Katmanlar sapmaya göre büyür/küçülür",28,h-30,p);}}
}
